### PR TITLE
fix(base-driver): supportedLogTypes does not get overwritten

### LINKED ISSUE #16738: supportedLogTypes does not get assigned properly on driver init since beta27
## The problem

After base driver update to 8.4.0 `getLogTypes` and `getLog` commands of appium-android-driver stopped working properly because `this.supportedLogTypes` property does not get initialized. I assume this is related to the recent typing refactoring in `base-driver/lib/basedriver/commands/log.js`. Previously this variable has been assigned by defining `extensions.supportedLogTypes`, which was equal to `{}` by default and is overridden in each driver if necessary. Now it always equals to `{}`. See https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=20705&view=logs&j=12e12a94-6f82-50bd-49c9-566fb2052675&t=7ba1c276-5935-513a-f217-d07020732771 for more details.

## Environment

* Appium version (or git revision) that exhibits the issue: base-driver 8.3.0
* Last Appium version that did not exhibit the issue (if applicable): base-driver 8.4.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

### PR DESCRIPTION
**Pull request by boneskull**
Closes #16738

There's a difference between assigning things to a prototype and public class fields, evidently.

To test this would be best done via interaction between drivers and `base-driver`, but affected drivers do not necessarily run the reusable test suite.  Fundamentally, a unit test for this would be testing Babel.  Unsure of best way to add an E2E test

Once it gets merged, we should publish as soon as possible, since @mykola-mokhnach is blocking on this.

### CODE REVIEW

File: packages/base-driver/lib/basedriver/commands/log.js [hunk 1]
```diff
@@ -13,11 +13,12 @@ export function LogMixin (Base) {
...
-    /**
-     * XXX: dubious
-     * @type {Record<string,LogType<Driver>>}
-     */
-    supportedLogTypes;
+
+    constructor (...args) {
+      super(...args);
+      /** @type {Record<string, LogType<Driver>>} */
+      this.supportedLogTypes = this.supportedLogTypes ?? {};
```
Comment (mykola-mokhnach) [inline packages/base-driver/lib/basedriver/commands/log.js:20]: I'm not quite sure about this expression. Do we assign the variable to itself?

Comment (boneskull) [reply packages/base-driver/lib/basedriver/commands/log.js:20]: it's this:

```js
if (this.supportedLogTypes === null || this.supportedLogTypes === undefined) {
  this.supportedLogTypes = {};
}
```

**Review by mykola-mokhnach — APPROVED** [review]

File: packages/base-driver/lib/basedriver/commands/log.js (hunk 1 above)
Comment (mykola-mokhnach) [reply packages/base-driver/lib/basedriver/commands/log.js:20]: I was just not quite sure how "this.supportedLogTypes" gets assigned before the constructor

**Review by jlipps — APPROVED** [review]

File: packages/base-driver/lib/basedriver/commands/log.js (hunk 1 above)
Comment (jlipps) [reply packages/base-driver/lib/basedriver/commands/log.js:20]: seems like it's just a safety mechanism because we can't rule out that it might have been set in some other "mixin"'s constructor and if it has, we leave it alone?

Comment (boneskull) [reply packages/base-driver/lib/basedriver/commands/log.js:20]: No, it doesn't have anything to do with mixins potentially setting the value.  `this.supportedLogTypes` is assigned before the constructor if it is on the constructor's `prototype`.  In the case of `AndroidDriver`, this is the case.  

What Babel seems to do (and this may be correct behavior) is a class field, e.g.,:

```js
class Foo {
  bar = 'baz'
}
```

actually results in this:

```
class Foo {
  constructor() {
     this.bar = 'foo';
  }
}
```

Now, that's fine if something subclasses `Foo` and then assigns its own value:

```js
class Baz extends Foo
  constructor() {
    super();
    this.bar = 'baz';
  }
}
```

or uses a field itself:

```js
class Baz extends Foo {
  bar = 'baz';
}
```

...but the above code is not the same as this (which is what `AndroidDriver` does, and maybe other drivers as well):

```js
class Baz extends Foo {}
Baz.prototype.bar = 'baz';
```

In the above case, the constructor for `Foo` will overwrite `Baz.prototype.bar` on any newly-instantiated `Baz` object.

What this means is we need to be careful with class fields, because unless a subclass _also_ uses class fields (or assignments in its constructor), we'll run into this problem.

Comment (boneskull) [reply packages/base-driver/lib/basedriver/commands/log.js:20]: actually, the android driver does something _really_ weird, which is assigns to its own prototype in its constructor (why?).  however, changing it to assign to the prototype after the `class` definition didn't fix the issue.

Comment (boneskull) [reply packages/base-driver/lib/basedriver/commands/log.js:20]: Here's a playground link to see for yourself how this happens:

https://www.typescriptlang.org/play?filetype=js#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE7QF5oByAM0WIG5V1MAXeAZTtwEsA7AcwAoBKFWpky4ApnQCuudtDoALVhAB0OXNSEBfVJtShIMAEJgAXtBEAPOiPYATGAiRohKwiRxHiWmrqjQAiuPEzUwsrWzhEAU9-QMUAB1x4BjoAT1iRZTwXYgBHALMqL3h2CHgQdJB4HgADQyMALmgAEmR2EQB3aFq+dSreamAikrLFCuroswbm1o7x7t7KaAB6RegAdQAJAE1oAElGaAAVdb3oKvJ4KoB+S5ogA

**Comment by jlipps** [comment]
I think we should probably fix the android driver and any other driver that assigns to prototypes to do something different, yeah?
