### PR TITLE
fix: appium:options should work via --default-capabilities

### LINKED ISSUE #18191: bug: appium 2.0.0-beta53 seems to ignore `appium:options` object
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`derivedDataPath` and `usePrebuiltWDA` setting seems to be ignored in appium 2.0.0-beta53 - `xcodebuild test-without-building` call doesn't use provided values. 

Appium 2.0.0-beta53 seems to also ignore other caps provided in `appium:options`, i.e. `connectHardwareKeyboard`. This method was working for 2.0.0-beta44.

Appium beta53 CLI call: `Appium command is: /Volumes/Sauce/selenium/appium-v2.0.0-beta53/node-darwin --max_old_space_size=1024 /Volumes/Sauce/selenium/appium-v2.0.0-beta53 --log-timestamp --callback-address 127.0.0.1 --address 127.0.0.1 --port 4443 --log-no-colors --default-capabilities {"appium:options": {"usePrebuiltWDA": true, "preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "derivedDataPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta53-xcode13.0/WebDriverAgent/DerivedData/WebdriverAgent", "bootstrapPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta53-xcode13.0/WebDriverAgent", "maxTypingFrequency": 8, "newCommandTimeout": 0, "connectHardwareKeyboard": true, "simulatorPasteboardAutomaticSync": "on", "app": "/var/folders/z9/rg8m2_gs5yq64gd5h71df2cc0000kr/T/tmpC2WXHT/TestApp7.2.app.zip", "keepKeyChains": true}} --relaxed-security --base-path /wd/hub`

Appium beta44 CLI call: `Appium command is: /Volumes/Sauce/selenium/appium-v2.0.0-beta44-separate-homes/node-darwin --max_old_space_size=1024 /Volumes/Sauce/selenium/appium-v2.0.0-beta44-separate-homes --log-timestamp --callback-address 127.0.0.1 --address 127.0.0.1 --port 4443 --log-no-colors --default-capabilities {"appium:options": {"usePrebuiltWDA": true, "preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "derivedDataPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta44-xcode14.0/WebDriverAgent/DerivedData/WebdriverAgent", "maxTypingFrequency": 8, "newCommandTimeout": 0, "connectHardwareKeyboard": true, "simulatorPasteboardAutomaticSync": "on", "app": "/var/folders/z9/rg8m2_gs5yq64gd5h71df2cc0000kr/T/tmpkPWe1U/TestApp7.2.app.zip", "keepKeyChains": true}} --relaxed-security --base-path /wd/hub`

### Expected Behavior

Appium should use provided `derivedDataPath` to pass it to `xcodebuild test-without-building` call.

### Minimal Reproducible Example

Start any session with `derivedDataPath` and `usePrebuiltWDA` inside `appium:options` caps.

### Environment

All informations in attached gist.

### Link to Appium Logs

https://gist.github.com/radoslaw-karasinski-sauce/3bac813bf3080f05cae22cd15ff0a8e7

### Futher Information

_No response_

### PR DESCRIPTION
**Pull request by jlipps**
fix #18191

### CODE REVIEW

**Comment by jlipps** [comment]
this is in draft because i need some types help from @boneskull (see the line that currently says `@ts-ignore`). mind pulling this down to see how to fix it?

File: packages/base-driver/lib/basedriver/capabilities.js [hunk 1]
```diff
@@ -334,77 +334,86 @@ function processCapabilities(
...
+    log.warn(
+      `Found capabilities inside ${PREFIXED_APPIUM_OPTS_CAP} that will overwrite ` +
+        `capabilities at the top level: ${JSON.stringify(overwrittenKeys)}`
+    );
+  }
+  // @ts-ignore
+  return _.cloneDeep({
+    ..._.omit(obj, PREFIXED_APPIUM_OPTS_CAP),
+    ...preprocessedOptions,
+  });
```
Comment (boneskull) [inline packages/base-driver/lib/basedriver/capabilities.js:396]:
```suggestion
  return _.cloneDeep({
    .../** @type {NSCapabilities<C>} */(_.omit(obj, PREFIXED_APPIUM_OPTS_CAP)),
    ...preprocessedOptions,
  });
```

File: packages/base-driver/lib/basedriver/capabilities.js [hunk 2]
```diff
@@ -334,77 +334,85 @@ function processCapabilities(
...
 /**
- * Return a copy of a capabilities object which has taken everything within the 'options'
- * capability and promoted it to the top level.
+ * Return a copy of a "bare" (single-level, non-W3C) capabilities object which has taken everything
+ * within the 'appium:options' capability and promoted it to the top level.
  *
  * @template {Constraints} C
- * @param {import('@appium/types').W3CCapabilities<C>} originalCaps
- * @return {import('@appium/types').W3CCapabilities<C>} the capabilities with 'options' promoted if necessary
+ * @param {NSCapabilities<C>} obj
```
Comment (boneskull) [inline packages/base-driver/lib/basedriver/capabilities.js:341]: I am not sure this is quite right.  I think what it expects is something more like:

```ts
NSCapabilities<C> & {'appium.options'?: Record<string,any>}
```

because NSCapabilities does not know anything about `appium:options` (I remember we discussed this).  If you do this, on L381 you won't need a type assertion to `string`, since it will be known that the keys are strings.

**Review by boneskull — APPROVED** [review]

File: packages/appium/test/e2e/driver.e2e.spec.js [hunk 3]
```diff
@@ -169,6 +169,53 @@ describe('FakeDriver via HTTP', function () {
...
+        value.should.exist;
+        value.capabilities.should.deep.equal({
+          automationName: 'Fake',
+          platformName: 'Fake',
+          deviceName: 'Fake',
+          app: TEST_FAKE_APP,
+        });
+      } finally {
+        // End session
+        await axios.delete(`${testServerBaseSessionUrl}/${value.sessionId}`);
```
[the remark this answers is not in the document]
Comment (jlipps) [reply packages/appium/test/e2e/driver.e2e.spec.js:214]: idk, good hygiene? what if we add another test to this block later?
