### PR TITLE
fix(support): path to APPIUM_HOME must always be absolute

### LINKED ISSUE #17338: extension resolution potentially broken when APPIUM_HOME is a relative path
I noticed while testing a plugin that when `APPIUM_HOME=../some/relative/path`, resolution of the extension breaks, because the module resolution begins within the `appium` install itself (`extension-config.js`).  

`APPIUM_HOME` must be converted to an absolute path as soon as it's determined.  That would happen in `env.js` of `@appium/support`.

### PR DESCRIPTION
**Pull request by boneskull**
Closes #17338

### CODE REVIEW

File: packages/support/lib/env.js [hunk 1]
```diff
@@ -112,21 +112,23 @@ export const readPackageInDir = _.memoize(
...
   async function _resolveAppiumHome(cwd = process.cwd()) {
-    if (process.env.APPIUM_HOME) {
-      return process.env.APPIUM_HOME;
-    }
-
     if (!path.isAbsolute(cwd)) {
       throw new TypeError('`cwd` parameter must be an absolute path');
     }
 
+    if (process.env.APPIUM_HOME) {
```
Comment (mykola-mokhnach) [inline packages/support/lib/env.js:128]: should we also validate if `process.env.APPIUM_HOME` is a relative path?

Comment (boneskull) [reply packages/support/lib/env.js:128]: If it's an absolute path, `path.resolve(someAbsolutePath, process.env.APPIUM_HOME)` will just be `process.env.APPIUM_HOME`.  If it's relative, then `path.resolve()` will make it absolute.  I don't see any need to check if it's relative before performing `path.resolve()`.

**Review by mykola-mokhnach — APPROVED** [review]

File: packages/support/lib/env.js (hunk 1 above)
Comment (mykola-mokhnach) [reply packages/support/lib/env.js:128]: this was not obvious to me

**Review by jlipps — APPROVED** [review]
