### PR TITLE
fix(appium,fake-driver): expose child process when running an extension script

### LINKED ISSUE #18211: bug: appium driver run scripts can't handle stdin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Interoperability with prompt managers like inquirer don't work

### Expected Behavior

I would expect a driver author to be able to do pretty much anything in a driver script including ask for CLI input

### Minimal Reproducible Example

n/a

### Environment

n/a

### Link to Appium Logs

_No response_

### Futher Information

_No response_

### PR DESCRIPTION
**Pull request by boneskull**
This change makes it so when running an extension script (e.g., `appium driver foo run some-script`), unless the `--json` flag is present, the child process will do no buffering whatsoever and will inherit `process.stdin`, `process.stdout` and `process.stderr` from Appium.

This means that extension scripts can do stuff like prompt the user for input.  It _also_ means they can do stuff like display progress bars and spinners.

If the user wants JSON data, we revert to the old behavior, which is to buffer the output and dump it once the script has completed.  I still don't understand why we need a `RingBuffer` there, since it seems like it could obliterate JSON output.  I didn't want to touch it though; Chesterton's fence & all that.

* * *

Note that given `teen_process`' `Promise`-based architecture--even using `teen_process.SubProcess`--there's still buffering and wrapping happening and I could not figure out how to make `teen_process` work the way I needed it to.  Maybe the lesson I've learned is that `teen_process` has a specific common use-case in mind--and it is not this one.

### CODE REVIEW

**Comment by boneskull** [comment]
> I still don't understand why we need a RingBuffer there, since it seems like it could obliterate JSON output

or rather, assuming it's used as an extra buffer on top of whatever is stuck in the stream, maybe it won't break JSON, but even then I'm not sure why it's needed.

File: packages/appium/lib/cli/extension-command.js [hunk 1]
```diff
@@ -699,26 +717,54 @@ class ExtensionCommand {
...
+      try {
+        await new B((resolve, reject) => {
+          this._runUnbuffered(
+            this.config.getInstallPath(installSpec),
+            extScripts[scriptName],
+            extraArgs
+          )
+            .on('error', (err) => {
+              // generally this is of the "I can't find the script" variety
+              reject(err);
```
Comment (mykola-mokhnach) [inline packages/appium/lib/cli/extension-command.js:752]: sometimes native errors are quite cryptic for users, e.g. ENOENT one.
Shall we add some customization on top of this one?

File: packages/fake-driver/lib/scripts/fake-stdin.js [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+const rl = readline.createInterface({input: process.stdin, output: process.stderr});
+
+rl.question('Press ENTER to continue: ', () => {
+  rl.close();
+  // eslint-disable-next-line no-console
+  console.error('You did it!');
+});
+
+rl.once('close', () => {
+  // there is some sort of weirdness where Node.js doesn't know when to stop listening on `process.stdin` if
```
Comment (mykola-mokhnach) [inline packages/fake-driver/lib/scripts/fake-stdin.js:12]: perhaps we just need to feed `eof` into the stream?
Are you sure `unref`'ing it won't create a memory leak?

Comment (mykola-mokhnach) [reply packages/fake-driver/lib/scripts/fake-stdin.js:12]:
```
const { spawn } = require('node:child_process');
const ps = spawn('ps', ['ax']);
const grep = spawn('grep', ['ssh']);

ps.stdout.on('data', (data) => {
  grep.stdin.write(data);
});

ps.stderr.on('data', (data) => {
  console.error(`ps stderr: ${data}`);
});

ps.on('close', (code) => {
  if (code !== 0) {
    console.log(`ps process exited with code ${code}`);
  }
  grep.stdin.end();
});

grep.stdout.on('data', (data) => {
  console.log(data.toString());
});

grep.stderr.on('data', (data) => {
  console.error(`grep stderr: ${data}`);
});

grep.on('close', (code) => {
  if (code !== 0) {
    console.log(`grep process exited with code ${code}`);
  }
});
```

An example from https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18293** <a href="https://app.graphite.dev/github/pr/appium/appium/18293" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/18293?utm_source=stack-comment).

File: packages/appium/lib/cli/extension-command.js [hunk 3]
```diff
@@ -699,26 +717,54 @@ class ExtensionCommand {
...
-      return {error: err.message, output: output.getBuff()};
+      try {
+        await runner.join();
+        this.log.ok(`${scriptName} successfully ran`.green);
+        return {output: output.getBuff()};
+      } catch (err) {
+        this.log.error(`Encountered an error when running '${scriptName}': ${err.message}`.red);
+        return {error: err.message, output: output.getBuff()};
+      }
+    } else {
```
Comment (jlipps) [inline packages/appium/lib/cli/extension-command.js:742]: given that we return in the block above, we don't really need the `else` and can save a level of indentation

**Review by jlipps — APPROVED** [review]
not sure about @mykola-mokhnach's questions about unref, but otherwise LGTM

File: packages/appium/lib/cli/extension-command.js (hunk 1 above)
Comment (boneskull) [reply packages/appium/lib/cli/extension-command.js:752]: It's not actionable by the user; it's a developer bug.  This means "the script file that the developer said would be there is not there"--not that the script isn't defined.

File: packages/fake-driver/lib/scripts/fake-stdin.js (hunk 2 above)
Comment (boneskull) [reply packages/fake-driver/lib/scripts/fake-stdin.js:12]: Why would `unref` cause a memory leak?  There's a bug around this, which is why I did what I did: https://github.com/nodejs/node/issues/32291

Comment (boneskull) [reply packages/fake-driver/lib/scripts/fake-stdin.js:12]: Anyway, the `end()` seems to work in lieu of `unref()`, so I'll just use that.
