### PR TITLE
fix #4825 context switching on real safari

### LINKED ISSUE #4825: Switching context on real ios device.
Hi Guys,

I am running a test on real ios device using ios-webkit-debug-proxy.
My appium version is 1.3.4 from source. The ios webkit is built from source - https://github.com/jchuong/ios-webkit-debug-proxy. Device is iPad Mini with ios 8.0.2.

In the framework I have implemented appium java client, so the driver is chosen according to the platform (IOS or Android). 
The test I'm running uses context method which allows me to change orientation of the browser, something like this: 

> driver.context("NATIVE_APP"); 
> driver.rotate(ScreenOrientation.LANDSCAPE); 
> driver.context("WEBVIEW_1"); 

Rotate does not work for me without changing context to NATIVE_APP and then recovering back to WEBVIEW. It all works great on a real android device using chrome, also does the job on ios simulator using safari, but using the real device on ios using safari it changes the orientation to landscape, but as soon as it tries to jump back to WEBVIEW context it throws an exception. 

Java exception: ERROR running Appium command: Cannot call method 'disconnect' of null
Appium exception:
>"info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('LANDSCAPE')"
>info: [debug] Sending command to instruments: au.setScreenOrientation('LANDSCAPE')
>info: [debug] [INST] 2015-03-31 16:01:59 +0000 Debug: Got new command 3 from instruments: au.setScreenOrientation('LANDSCAPE')
>info: [debug] [INST] 2015-03-31 16:01:59 +0000 Debug: evaluating au.setScreenOrientation('LANDSCAPE')
>info: [debug] [INST] 2015-03-31 16:01:59 +0000 Debug: target.setDeviceOrientation("3")
>info: [debug] [INST] 2015-03-31 16:02:00 +0000 Debug: evaluation finished
>info: [debug] [INST] 2015-03-31 16:02:00 +0000 Debug: responding with:
>info: [debug] [INST] 2015-03-31 16:02:00 +0000 Debug: Running system command #4: /usr/local/bin/node  /node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock >2,{"status":0,"value":"LANDSCAPE"}...
>info: [debug] Socket data received (34 bytes)
>info: [debug] Socket data being routed.
>info: [debug] Got result from instruments: {"status":0,"value":"LANDSCAPE"}
>info: [debug] Responding to client with success: {"status":0,"value":"LANDSCAPE","sessionId":"54c2e114-e8c0-44b7-9d86-56d340b6bcc6"}
>info: <-- POST /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/orientation 200 1673.418 >ms - 83 {"status":0,"value":"LANDSCAPE","sessionId":"54c2e114-e8c0-44b7-9d86-56d340b6bcc6"}
info: --> POST /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/context {"name":"WEBVIEW_1"}
info: [debug] Attempting to set context to 'WEBVIEW_1'
TypeError: Cannot call method 'disconnect' of null
    at null.<anonymous> ( /lib/devices/ios/ios-controller.js:1619:27)
    at null.<anonymous> ( /lib/devices/ios/ios-controller.js:1631:9)
    at iOSController.setContext ( /lib/devices/ios/ios-controller.js:1646:7)
    at Object.exports.setContext [as handle] ( /lib/server/controller.js:1005:16)
    at next_layer ( /node_modules/express/lib/router/route.js:113:13)
    at Route.dispatch ( /node_modules/express/lib/router/route.js:117:5)
    at  /node_modules/express/lib/router/index.js:222:24
    at param ( /node_modules/express/lib/router/index.js:307:14)
    at param ( /node_modules/express/lib/router/index.js:323:14)
    at Function.proto.process_params ( /node_modules/express/lib/router/index.js:367:3)
info: <-- POST /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/context 500 2.615 ms - 93 
info: --> POST /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/url {"url":"https://mywebsite"}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"54c2e114-e8c0-44b7-9d86-56d340b6bcc6"}
info: <-- POST /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/url 200 2.169 ms - 74 {"status":0,"value":"","sessionId":"54c2e114-e8c0-44b7-9d86-56d340b6bcc6"}
info: --> GET /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/window_handle {}
info: [debug] Responding to client that a method is not implemented in this context
info: <-- GET /wd/hub/session/54c2e114-e8c0-44b7-9d86-56d340b6bcc6/window_handle 501 3.613 ms - 159 
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"safari","elementScrollBehavior":true,"acceptSslCerts":true,"browserName":"safari","launch":"true","rotatable":true,"version":"7.0","platformVersion":"8.1.2","deviceName":"iPhone 5s","platformName":"iOS","nonSyntheticWebClick":false,"nativeEvents":true,"device":"iPhone 5s","hasTouchScreen":true}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: Found an existing session to clobber, shutting it down first...
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-03-31 16:01:55 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] Instruments Trace Complete (Duration : 36.398785s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Cleaning up appium session
info: Old session shut down OK, proceeding to new session"

When this happens one of the following scenarios is true: 
- test fails and next one is being executed as normal
- test fails and my ios_webkit_debug_proxy is being disconnected from device which means tests are no longer running
- test fails and appium hangs and waits for a long timeout 
(appium output: info: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Trying to stop instruments but it already exited
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Cleaning up appium session
info: [debug] We shut down because no new commands came in)

after 10 minutes java output: org.openqa.selenium.remote.SessionNotFoundException:
Command duration or timeout: 602.01 seconds

Did a little bit of investigating to try and solve the issue, kind of got a work around but it's not a nice fix. Basically commenting out line 1581 'this.remote = null;' in ios-controller.js : 

>else {
      this.curContext = null;
      //TODO: this condition should be changed to check if the webkit protocol is being used.
      if (this.args.udid) {
        this.remote.disconnect();
        //This is commented out due to work in progress regarding context switching on real iOS device
        //this.remote = null;
      }

helped to get the test going through and new test starting, but sometimes ios-webkit is disconnecting or appium hangs.
TODO note seems that there is still some work needed in regards to real device.

What do you guys think?

### PR DESCRIPTION
**Pull request by Jonahss**

### CODE REVIEW

File: test/functional/ios/webview/basics-specs.js [hunk 1]
```diff
@@ -38,26 +38,18 @@ describe('webview - basics', function () {
...
-      .contexts().should.eventually.have.length.above(0)
-      .context("WEBVIEW_1")
-      .sleep(500)
-      .get(env.GUINEA_TEST_END_POINT)
-      .sleep(500)
-      .title()
-      .should.eventually.equal("I am a page title")
-      .nodeify(done);
-  });
-  it('setting context to \'WEBVIEW_1\' should work without first getting contexts', function (done) {
```
Comment (imurchie) [inline test/functional/ios/webview/basics-specs.js]: By getting rid of this test are we admitting that the only correct pattern for changing contexts is to get the contexts first?  For tests on a simulator it works to hard code the context, so this _could_ just be sequestered from real device tests, and we would know that we could, should we want to, set a context without first getting the list.

Comment (Jonahss) [inline test/functional/ios/webview/basics-specs.js]: Ah ok :) we have an @skip-real-device tag I can use.

**Comment by Jonahss** [comment]
@imurchie re-added that test, and set it to not get contexts.
