### PR TITLE
fix(appium): fix extension autoinstall postinstall script

### LINKED ISSUE #16924: appium's postinstall is broken
It looks like it was not updated correctly as files were moved and migrated. 

Repro:
```
cd packages/appium/scripts
npm_config_drivers=xcuitest,uiautomator2 node ./postinstall.js
```

### PR DESCRIPTION
**Pull request by boneskull**
Resolves #16924

* * *

- This is a little more involved than I would have liked.  Maybe it'd make more sense to just spawn e.g., `appium driver install` child processes?
- Since this script exits with a non-zero code, it can prevent installation of Appium altogether, which seems undesirable.

### CODE REVIEW

File: packages/appium/scripts/postinstall.js [hunk 1]
```diff
@@ -14,20 +17,34 @@ async function main () {
...
+  const {loadExtensions} = require('../build/lib/extension');
   const {runExtensionCommand} = extension;
-  const appiumHome = process.env.npm_config_appium_home || DEFAULT_APPIUM_HOME;
-  const specs = [[DRIVER_TYPE, driverEnv], [PLUGIN_TYPE, pluginEnv]];
+  const specs = [
+    [DRIVER_TYPE, driverEnv],
+    [PLUGIN_TYPE, pluginEnv],
+  ];
+
+  const appiumHome = process.env.npm_config_appium_home || (await env.resolveAppiumHome());
```
Comment (mykola-mokhnach) [inline packages/appium/scripts/postinstall.js:33]: shouldn't `npm_config_appium_home` be also considered in `resolveAppiumHome` call?

File: packages/appium/scripts/postinstall.js [hunk 2]
```diff
@@ -36,35 +53,41 @@ async function main () {
...
-    suppressOutput: true,
-  }, type);
+  await runExtensionCommand(
+    {
+      appiumHome,
+      [`${type}Command`]: 'install',
+      suppressOutput: true,
+      [type]: ext,
+    },
+    type === 'driver' ? driverConfig : pluginConfig
```
Comment (mykola-mokhnach) [inline packages/appium/scripts/postinstall.js:85]: magic string?

File: packages/appium/scripts/postinstall.js (hunk 1 above)
Comment (boneskull) [reply packages/appium/scripts/postinstall.js:33]: I'm not sure what you're asking.  Are you asking if `resolveAppiumHome()` should consider that environment variable in addition to `APPIUM_HOME`?

Comment (mykola-mokhnach) [reply packages/appium/scripts/postinstall.js:33]: yes, exactly

**Comment by boneskull** [comment]
I've updated the `postinstall.js` script to _never_ exit with a non-zero code; errors will be displayed, but the installation will continue.

File: packages/appium/scripts/postinstall.js (hunk 1 above)
Comment (jlipps) [reply packages/appium/scripts/postinstall.js]: i think we settled on just leaning on APPIUM_HOME. i think this code came from a time when we had the `--appium-home` command line flag, and it mirrors that. but we no longer have that flag.

File: packages/appium/scripts/postinstall.js [hunk 3]
```diff
@@ -10,23 +23,15 @@ async function main() {
...
-  const {DEFAULT_APPIUM_HOME, DRIVER_TYPE, PLUGIN_TYPE} = require('./build/lib/extension-config');
-  const {runExtensionCommand} = extension;
-  const appiumHome = process.env.npm_config_appium_home || DEFAULT_APPIUM_HOME;
   const specs = [
     [DRIVER_TYPE, driverEnv],
     [PLUGIN_TYPE, pluginEnv],
   ];
 
+  const appiumHome =
+    process.env.npm_config_appium_home || (await env.resolveAppiumHome());
```
Comment (jlipps) [inline packages/appium/scripts/postinstall.js:32]: i *think* we can do away with this appium home npm install flag and just rely on APPIUM_HOME or the standard env discovery.

**Review by jlipps — APPROVED** [review]
i'm not sure if the right thing is actually to prevent installation of appium? i mean if someone requests drivers as part of the install, usually in a CI environment, wouldn't they want to know if those drivers werent installed before running their tests?

**Comment by boneskull** [comment]
@jlipps 

> i'm not sure if the right thing is actually to prevent installation of appium? i mean if someone requests drivers as part of the install, usually in a CI environment, wouldn't they want to know if those drivers werent installed before running their tests?

How about a compromise: fail if `process.env.CI`?

File: packages/appium/scripts/postinstall.js (hunk 3 above)
Comment (boneskull) [reply packages/appium/scripts/postinstall.js]: OK.  Though ... I see a problem I hadn't thought of before.

This script is only applicable if Appium _isn't_ a direct dependency within the closest `package.json`. If that's the case, then it's expected these drivers/plugins will _also_ be direct dependencies.

I'll address this

**Comment by boneskull** [comment]
I made it nicer.   Here's some screenshots, but there's also _spinners_:

image

image

image

File: packages/appium/scripts/postinstall.js [hunk 4]
```diff
@@ -1,83 +1,162 @@
...
 
-  let extension;
-  try {
-    extension = require('../build/lib/cli/extension');
-  } catch (e) {
-    throw new Error(
-      `Could not load extension CLI file; has the project been transpiled? ` + `(${e.message})`
+  if (!driverEnv && !pluginEnv) {
+    spinner.succeed(
+      `No drivers or plugins to automatically install. If desired, set the "npm_config_drivers" or "npm_config_plugins" environment variable(s) to a comma-separated list, and they will be installed automatically with Appium.`
```
Comment (jlipps) [inline packages/appium/scripts/postinstall.js:62]: NPM sets these env vars. What the user does is add them as flags to npm install, e.g.,

```
npm install -g appium --drivers=fake,xcuitest
```

then NPM magically turns `--drivers` into `process.env.npm_config_drivers`.

all that to say, we should probably refer to the `--drivers` and `--plugins` way of doing things because that is the intended user facing feature.

**Review by jlipps — CHANGES_REQUESTED** [review]
looks good, one comment

File: packages/appium/scripts/postinstall.js (hunk 4 above)
Comment (boneskull) [reply packages/appium/scripts/postinstall.js:62]: Ah, k.

**Review by jlipps — APPROVED** [review]
LGTM when CI passes

**Comment by boneskull** [comment]
ugh what have I done

**Comment by boneskull** [comment]
OK, so basically: we can't require anything from `@appium/support` here because it won't have been built yet.  The `postinstall` scripts in the subpackages run before the postinstall script in the monorepo.  I think what we can do is add `prepare` scripts to each subpackage which call `npm run build`. These `prepare` scripts only get called before publish and on an `npm install` in a working copy.

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* 2.0
  * **PR #16902** <a href="https://app.graphite.dev/github/pr/appium/appium/16902" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/16925?utm_source=stack-comment).

**Review by jlipps — APPROVED** [review]

File: package.json [hunk 5]
```diff
@@ -98,7 +97,8 @@
     "@appium/test-support": "file:packages/test-support",
     "@appium/types": "file:packages/types",
     "@appium/universal-xml-plugin": "file:packages/universal-xml-plugin",
-    "appium": "file:packages/appium"
+    "appium": "file:packages/appium",
+    "lru-cache": "7.9.0"
```
[the remark this answers is not in the document]
Comment (boneskull) [reply package.json:101]: hmm, I was trying to fix the `lru-cache` bug.  I'll rip that out and try again.

[the remark this answers is not in the document]
Comment (boneskull) [reply package.json]: yeah, wasn't needed.
