### PR TITLE
many fixes to emit working declarations

### LINKED ISSUE #18379: base-driver: bad declarations (and the prevention thereof)
So the declarations generated from `@appium/base-driver` have some sort of bug in them. For whatever reason, `BaseDriver` ends up _extending multiple classes_. 

This is probably a bug in TypeScript, but I don't think I have the gumption to get at the root cause.

My hunch is that it is JS-specific. The first step I'd take is to see if we can't convert the `driver.js` source to TypeScript. 

This was discovered by pulling in the declarations from a project where the TS compiler config has `skipLibCheck: false`. 

To avoid this sort of thing in the future, pulling in a small type-testing framework should be sufficient. Whatever the DefinitivelyTyped project uses should be adequate.

### PR DESCRIPTION
**Pull request by boneskull**
This fixes the invalid declarations generated by TypeScript by rewriting `@appium/base-driver`'s
`lib/basedriver/driver.js` (containing the `BaseDriver` class) in TypeScript.

It also addresses a host of issues found when doing so, particularly around the use of the
`*Capabilities` and `*DriverCaps` types.  The question of which of these an external driver should
use is much less murky (e.g., you want to use `createSession(caps: W3CDriverCaps<MyConstraints>)`).
See the detailed commit message for more information.

It builds upon the structure added in #18390 by adding handful of simple checks for `BaseDriver`.

Closes #18379

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18390** <a href="https://app.graphite.dev/github/pr/appium/appium/18390" target="_blank">Graphite</a> 
    * **PR #18391** <a href="https://app.graphite.dev/github/pr/appium/appium/18391" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/18391?utm_source=stack-comment).

**Review by mykola-mokhnach — APPROVED** [review]

File: packages/base-driver/lib/protocol/routes.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ const SET_ALERT_TEXT_PAYLOAD_PARAMS = {
  * define the routes, mapping of HTTP methods to particular driver commands, and
  * any parameters that are expected in a request parameters can be `required` or
  * `optional`
+ * @satisfies {import('@appium/types').MethodMap<import('../basedriver/driver').BaseDriver>}
```
Comment (jlipps) [inline packages/base-driver/lib/protocol/routes.js:21]: oh cool, is this new?

**Review by jlipps — APPROVED** [review]

File: packages/base-driver/lib/protocol/routes.js (hunk 1 above)
Comment (boneskull) [reply packages/base-driver/lib/protocol/routes.js:21]: yes!
