### PR TITLE
fix(appium): ensure appiumCliDest is recognized by config file normalizer

### LINKED ISSUE #17638: The log-level argument in the config file is not effective
## The problem

I have set this parameter to info in the configuration file , but it doesn't work.

## Environment

* Appium version: v2.0.0-beta.46
* Desktop OS/version used to run Appium: Windows10
* Node.js version: v16.17.1
* Npm or Yarn package manager: npm@8.19.2
* Appium CLI or Appium.app|exe:  CLI

## Details

The config from defaults is loglevel: 'debug' and theconfig from defaults is logLevel: 'info'. The actual log level is debug. But it is work if log-level is input through the cli.

## Link to Appium logs

https://gist.github.com/scxhwhb/c415fb5c85538a3a7c66d5609a64b11e

### PR DESCRIPTION
**Pull request by boneskull**
Closes #17638

Contains four (4) changesets:

1. Wherein I fix the actual bug
2. Wherein I rename a bunch of test fixtures
3. Wherein I squelch noisy E2E test output
4. Wherein I implement better assertions for config file E2E tests

### CODE REVIEW

**Comment by boneskull** [comment]
The tests need better assertions.  I'll move this out of draft when I update them (likely tomorrow)

File: packages/appium/test/e2e/e2e-helpers.js [hunk 1]
```diff
@@ -37,8 +37,10 @@ async function run(appiumHome, args, opts = {}) {
   opts.env = _.defaults(opts.env, {APPIUM_HOME: appiumHome, PATH: process.env.PATH});
   try {
     args = [...process.execArgv, '--', EXECUTABLE, ...args];
-    log.debug('APPIUM_HOME: %s', opts.env.APPIUM_HOME);
-    log.debug(`Running: ${process.execPath} ${args.join(' ')}`);
+    if (process.env._FORCE_LOGS) {
```
Comment (mykola-mokhnach) [inline packages/appium/test/e2e/e2e-helpers.js:40]: 👍

**Review by mykola-mokhnach — APPROVED** [review]

**Review by jlipps — APPROVED** [review]

**Review by KazuCocoa — APPROVED** [review]
